nameSuffix: -small
bases:
- ../base

commonLabels:
  app: memcached-small

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=1000       # 1k
  - records=1000000  # 1M        total = 1GB
  - qps=100000       # 100k
