nameSuffix: -medium

bases:
- ../base

commonLabels:
  app: redis-medium

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=50
    - threads=6
    - keymaximum=100000000
    - datasize=32
    - ratio=1:10
