nameSuffix: -medium

bases:
- ../base

commonLabels:
  app: redis-medium

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=100
    - threads=6
    - datasize=512
    - pipeline=10
    - ratio=1:10
