- name: first rule
  allocations:
    cpu_shares: 2.5
    cpu_quota: 0.5 
    rdt:
        name: ''
        l3: 'L3:0=fff;1=00fff'

- name: not for first task
  labels:
    job_uniq_id: '[01]'
  allocations:
    cpu_shares: 0.5
    cpu_quota: 1.
    rdt:
        name: 'be'
        l3: 'L3:0=1;1=fffff'
