- name: default rule for all
  allocations:
    # cpu_shares: 4.5
    # cpu_quota: 0.1 
    rdt:
        name: 
        l3: 'L3:0=00fff;1=0ffff'

- name: first task with label0
  labels:
    job_uniq_id: '0'
  allocations:
    cpu_shares: 0.5
    cpu_quota: 0.01
    rdt:
        name: 'be'
        l3: 'L3:0=00002;1=00002'
