nameSuffix: -medium

bases:
- ../base

commonLabels:
  app: sysbench-memory-medium

patchesStrategicMerge:
  - resources.yaml

configMapGenerator:
- name: sysbench-memory
  behavior: merge
  literals:
    - threads=8
    - memory=1g
    - report_interval=45