
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: monitoring


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: monitoring
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>
    <source>
      @type dummy
      tag dummy
      dummy {"hello":"world"}
    </source>
    <source>
      @type prometheus
    </source>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    <match kubernetes.var.log.containers.**monitoring**.log>
      @type null
    </match>
    <filter kubernetes.var.log.containers.**>
      @type prometheus
      <metric>
        name stdout_lines
        type counter
        desc Number of stdout lines
        <labels>
          hostname ${hostname}
          app $.kubernetes.labels.app
          workload $.kubernetes.labels.workload
        </labels>
      </metric>
    </filter>
    <filter dummy>
      @type prometheus
      <metric>
        name dummy_messages
        type counter
        desc The total number of incoming dummy messages
        <labels>
          tag ${tag}
          hostname ${hostname}
        </labels>
      </metric>
    </filter>
 #   <match **>
 #     @type stdout
 #   </match>

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      app: fluentd-logging
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluentd-logging
        version: v1
    spec:
      hostNetwork: true
      serviceAccount: fluentd
      serviceAccountName: fluentd
      nodeSelector:
        kubernetes.io/hostname: node14
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4-debian-forward-1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentconfig
          mountPath: /fluentd/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentconfig
        configMap:
          name: fluentdconf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
