---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd
configMapGenerator:
  - name: fconf
    files:
    - configurations/fluent.conf
    - configurations/stress.conf
    - configurations/mutilate.conf
    - configurations/sysbench.conf
    - configurations/memtier.conf
resources:
  - fluentd.yaml
