groups:
- name: SLOS
  rules:
  - record: apm__slo
    expr: 1200
    labels:
      app: mutilate
  - record: apm__sli
    expr: apm__mutilate_scan_read_p99 and rate(apm__mutilate_stdout_lines[5s])>0
    labels:
      app: mutilate
  - record: apm__slo
    expr: 3200
    labels:
      app: sysbench
  - record: apm__sli
    expr: apm__sysbench_qps and rate(apm__sysbench_stdout_lines[5s])>0
    labels:
      app: sysbench
  - record: apm__slo
    expr: 1000
    labels:
      app: stress_ng
  - record: apm__sli
    expr: apm__stress_ng_bogo_ops_per_second_usr_sys_time and rate(apm__stress_ng_stdout_lines[5s])>0
    labels:
      app: stress_ng
  - record: apm__slo
    expr: 1000
    labels:
      app: memtier
  - record: apm__sli
    expr:  apm__memtier_qps and rate(apm__memtier_stdout_lines[5s])>0
    labels:
      app: memtier
  - record: apm__sli_normalized
    expr: apm__sli / on (app) group_left apm__slo
