groups:
- name: SLOS
  rules:
# -------------Mutilate-----------------
  - record: apm__slo  # big
    expr: 700
    labels:
      app: memcached-big
  - record: apm__slo  # medium
    expr: 600
    labels:
      app: memcached-medium
  - record: apm__slo  # small
    expr: 500
    labels:
      app: memcached-small
  - record: apm__mutilate_alive
    expr: ceil(rate(apm__mutilate_stdout_lines[30s])>0)
  - record: apm__mutilate_qps
    expr: avg_over_time(apm__mutilate_scan_qps[60s]) and apm__mutilate_alive
  - record: apm__mutilate_latency
    expr: avg_over_time(apm__mutilate_scan_read_p99[60s]) and apm__mutilate_alive
  - record: apm__memcached_latency
    expr: (label_replace(apm__mutilate_latency, "task_name", "$1/memcached-$2", "task_name", "(.*)/mutilate-(.*)")) * on(task_name) group_right() (task__last_seen/task__last_seen)
  - record: apm__memcached_qps
    expr: (label_replace(apm__mutilate_qps, "task_name", "$1/memcached-$2", "task_name", "(.*)/mutilate-(.*)")) * on(task_name) group_right() (task__last_seen/task__last_seen)
  - record: apm__latency
    expr: apm__memcached_latency
  - record: apm__throughput
    expr: apm__memcached_qps
# -------------Sysbench-----------------
  - record: apm__slo  # big
    expr: 70000
    labels:
      app: sysbench-memory-big
  - record: apm__slo  # medium
    expr: 40000
    labels:
      app: sysbench-memory-medium
  - record: apm__slo  # small
    expr: 18000
    labels:
      app: sysbench-memory-small
  - record: apm__sysbench_mbps    # MiB/sec
    expr: avg(avg_over_time(apm__sysbench_qps[30s]) and (rate(apm__sysbench_stdout_lines[15s])>0)) by (app)
  - record: apm__throughput       # MiB/sec
    expr: apm__sysbench_mbps

# -------------Stress-----------------
  - record: apm__slo  # big
    expr: 10000
    labels:
      app: stress-stream-big
  - record: apm__slo
    expr: 100         # medium
    labels:
      app: stress-stream-medium
  - record: apm__slo
    expr: 1000        # small
    labels:
      app: stress-stream-small
  - record: apm__stress_bogo_ops
    expr: avg(rate(apm__stress_ng_bogo_ops_counter[30s]) and rate(apm__stress_ng_stdout_lines[15s]) > 0) by (app)
  - record: apm__throughput      # bogo/ops
    expr: apm__stress_bogo_ops


# -------------Memtier-----------------
  - record: apm__slo
    expr: 100000000
    labels:
      app: redis-small
  - record: apm__slo
    expr: 100000000
    labels:
      app: redis-medium
  - record: apm__slo
    expr: 100000000
    labels:
      app: redis-big
  - record: apm__sli
    expr: avg(rate(apm__memtier_ops[30s]) and rate(apm__memtier_stdout_lines[30s])>0) by (app)
  # intermediary
  - record: apm__memtier_alive
    expr: ceil(rate(apm__memtier_stdout_lines[30s])>0)
  - record: apm__memtier_ops
    expr: rate(apm__memtier_scan_operations[30s]) and apm__memtier_alive
  - record: apm__memtier_latency
    expr: avg_over_time(apm__memtier_scan_latency[60s]) and apm__memtier_alive
  # common apm metrics
  - record: apm__redis_latency
    expr: (label_replace(apm__memtier_latency, "task_name", "$1/redis-$2", "task_name", "(.*)/memtier-(.*)")) * on(task_name) group_right() (task__last_seen / task__last_seen)
  - record: apm__redis_qps
    expr: (label_replace(apm__memtier_ops, "task_name", "$1/redis-$2", "task_name", "(.*)/memtier-(.*)")) * on(task_name) group_right() (task__last_seen / task__last_seen)
  - record: apm__latency
    expr: apm__redis_latency
  - record: apm__throughput
    expr: apm__redis_qps

#---------------------------------------
  - record: apm__sli  #  SLI
    expr: apm__throughput
  - record: apm__sli_normalized
    expr: apm__sli / on (app) group_left apm__slo
