groups:
- name: SLOS
  rules:
# -------------Mutilate-----------------
  - record: apm__slo
    expr: 500
    labels:
      app: mutilate-small
  - record: apm__slo
    expr: 600
    labels:
      app: mutilate-medium
  - record: apm__slo
    expr: 700
    labels:
      app: mutilate-big
  - record: apm__sli
    expr: avg(apm__mutilate_scan_read_p99 and rate(apm__mutilate_stdout_lines[30s])>0) by (app)
# -------------Sysbench-----------------
  - record: apm__slo
    expr: 3200
    labels:
      app: sysbench-small
  - record: apm__slo
    expr: 3200
    labels:
      app: sysbench-medium
  - record: apm__slo
    expr: 3200
    labels:
      app: sysbench-big
  - record: apm__sli
    expr: avg(apm__sysbench_qps and rate(apm__sysbench_stdout_lines[30s])>0) by (app)
# -------------Stress-----------------
  - record: apm__slo
    expr: 1000        # small
    labels:
      app: stress-stream-small
  - record: apm__slo
    expr: 100         # medium
    labels:
      app: stress-stream-medium
  - record: apm__slo  # big
    expr: 100
    labels:
      app: stress-stream-big
  - record: apm__sli
    expr: avg(apm__stress_ng_bogo_ops_per_second_usr_sys_time and rate(apm__stress_ng_stdout_lines[30s])>0) by (app)
# -------------Memtier-----------------
  - record: apm__slo
    expr: 1000
    labels:
      app: memtier-small
  - record: apm__slo
    expr: 1000
    labels:
      app: memtier-medium
  - record: apm__slo
    expr: 1000
    labels:
      app: memtier-big
  - record: apm__sli
    expr:  apm__memtier_ops and rate(apm__memtier_stdout_lines[30s])>0
#---------------------------------------
  - record: apm__sli_normalized
    expr: apm__sli / on (app) group_left apm__slo
