# reload rules with
# promtool check rules /home/ppalucki/wca_remote_pycharm/example/k8s_monitoring/prometheus/prometheus.rules.yaml && pkill -HUP prometheus

groups:
# ----------------------------- APP -------------------------------------
- name: aep_apps
  rules:
  - record: app__memory_access_rate_over_15s
    expr: avg(rate(task__mem_inst_retired_all_loads__rd081[15s]) + rate(task__mem_inst_retired_all_stores__rd082[15s])) by (app) / 1e9
  - record: app__memory_bandwidth_rate_15s_gb
    expr: avg(rate(task__memory_bandwidth[15s])) by (app) / 1e9
  - record: app__wss_avg_15s_gb
    expr: avg(avg_over_time(task__wss_referenced_mb[15s])) by (app) / 1000
  - record: app__memory_access_locality
    expr: app__memory_bandwidth_rate_15s_gb / app__wss_avg_15s_gb
  - record: app__memory_rw_ratio
    expr: avg(task__memory_rw_ratio) by (app)
  - record: app__memory_intensivity
    expr: app__memory_bandwidth_rate_15s_gb / 100  # Assume all nodes has max 100GB membw
  - record: app__rss_15s_avg_gb
    expr: avg by(app) (avg_over_time(task__memory_usage_per_task_bytes[15s])) / 1e9

  # Cache utilization normalized to cluster avg_app_utilization
  - record: app__cache_utilization_normalized
    expr: app__cache_utilization / cluster__avg_app_utilization

  # Cache utilization = RW * (BW/WSS) * (BW/100)
  - record: app__cache_utilization
    expr: app__memory_access_locality * app__memory_rw_ratio * app__memory_intensivity

  # 2LM Friend = RW / (BW * WSS)
  - record: app__2lm_friend
    expr: app__memory_rw_ratio / (app__memory_bandwidth_rate_15s_gb*app__wss_avg_15s_gb)

  # RSS / WSS (2LM Friend v2)
  - record: app__rss_wss_ratio
    expr: app__rss_15s_avg_gb / app__wss_avg_15s_gb
  - record: app__wss_rss_ratio
    expr: app__wss_avg_15s_gb / app__rss_15s_avg_gb

# ----------------------------- NODE -------------------------------------
- name: aep_node
  rules:
  - record: node__dram_hit_15s
    expr: sum(avg_over_time(platform__dram_hit[15s])) by(node)
  - record: node__total_memory_stalls
    expr: sum by(node) (rate(task__memstalls__ra310[15s]))
  - record: node__total_wss
    expr: sum by(node) (task__wss_referenced_mb)
  - record: node__total_rss
    expr: sum by(node) (platform__memory_usage)
  - record: node__cache_contention
    expr: (1 - (node__dram_hit_15s * node__dram_hit_15s)) * 100
  - record: node__cache_contention_normalized
    expr: node__cache_contention / cluster__avg_cache_contention
  - record: node__cache_utilization_class
    expr: avg by(node) (avg_over_time(appnode__cache_utilization[15s]))

# ----------------------------- CLUSTER -------------------------------------
- name: aep_cluster
  rules:
  - record: cluster__avg_cache_contention
    expr: avg(node__cache_contention)
  - record: cluster__avg_app_utilization
    expr: avg(app__cache_utilization)

# ----------------------------- APPNODE -------------------------------------
- name: aep_appnode
  rules:
  - record: appnode__memory_bandwidth_rate_15s_gb
    expr: avg(rate(task__memory_bandwidth[15s])) by (app, node) / 1e9
  - record: appnode__wss_avg_15s_gb
    expr: avg(avg_over_time(task__wss_referenced_mb[15s])) by (app, node) / 1000
  - record: appnode__memory_intensivity
    expr: appnode__memory_bandwidth_rate_15s_gb / 100  # Assume all nodes has max 100GB membw
  - record: appnode__memory_access_locality
    expr: appnode__memory_bandwidth_rate_15s_gb / appnode__wss_avg_15s_gb
  - record: appnode__memory_rw_ratio
    expr: avg(task__memory_rw_ratio) by (app, node)
  - record: appnode__cache_utilization
    expr: appnode__memory_access_locality * appnode__memory_rw_ratio * appnode__memory_intensivity


# ----------------------------- FIT (according (node_cache_utilization-app_cache_utilization) -------------------------------------
- name: aep_apps_fits

  rules:
  - record: fit
    expr: abs( (app__wss_rss_ratio) - on() group_left(node) node__dram_hit_15s{node="node11"} )
    labels:
      mode: rsswss
  - record: fit
    expr: abs( (app__wss_rss_ratio) - on() group_left(node) node__dram_hit_15s{node="node12"} )
    labels:
      mode: rsswss
  - record: fit
    expr: abs( (app__wss_rss_ratio) - on() group_left(node) node__dram_hit_15s{node="node13"} )
    labels:
      mode: rsswss
  - record: fit
    expr: abs( (app__wss_rss_ratio) - on() group_left(node) node__dram_hit_15s{node="node14"} )
    labels:
      mode: rsswss

  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node11"})
    labels:
      mode: cacheutil
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node12"})
    labels:
      mode: cacheutil
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node13"})
    labels:
      mode: cacheutil
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node14"})
    labels:
      mode: cacheutil


  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node11"})
    labels:
      mode: 2lmfriend
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node12"})
    labels:
      mode: 2lmfriend
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node13"})
    labels:
      mode: 2lmfriend
  - record: fit
    expr: 1 / abs(app__cache_utilization - on() group_left(node) node__cache_utilization_class{node="node14"})
    labels:
      mode: 2lmfriend


####################################################################################
# DERIVED
####################################################################################

# ----------------------------- TASK_DERIVED -------------------------------------
- name: wca_task_derived
  rules:
  - record: task__dram_hit
    expr: task__mem_load_retired_local_dram__rd301 / (task__mem_load_retired_local_pmm__rd180 + task__mem_load_retired_local_dram__rd301)
  - record: task__memory_rw_ratio
    expr: rate(task__mem_inst_retired_all_loads__rd081[15s]) / rate(task__mem_inst_retired_all_stores__rd082[15s])


# ----------------------------- PLATFORM (derived) ---------------------------------
- name: wca_platform_derived
  rules:
  # PMM
  - record: platform__pmm_reads_mb_per_second
    expr: rate(platform__pmm_bandwidth_read[15s]) * 64 / 1e6
  - record: platform__pmm_writes_mb_per_second
    expr: rate(platform__pmm_bandwidth_write[15s]) * 64 / 1e6
  - record: platform__pmm_total_mb_per_second
    expr: platform__pmm_reads_mb_per_second + platform__pmm_writes_mb_per_second

  # DRAM
  - record: platform__dram_reads_mb_per_second
    expr: rate(platform__cas_count_read[15s]) * 64 / 1e6
  - record: platform__dram_writes_mb_per_second
    expr: rate(platform__cas_count_write[15s]) * 64 / 1e6
  - record: platform__dram_total_mb_per_second
    expr: platform__dram_reads_mb_per_second + platform__dram_writes_mb_per_second

  # HIT
  - record: platform__dram_hit
    expr: platform__dram_total_mb_per_second / (platform__pmm_total_mb_per_second + platform__dram_total_mb_per_second)


