nameSuffix: -big
bases:
- ../base

commonLabels:
  app: memcached-big

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=50000      # 50k
  - records=1000000  # 1M        total = 50GB
  - qps=1000000      # 2M

patchesStrategicMerge:
  - resources.yaml
