apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 3
              memory: 60G # valueSize*records = 50k * 1M = 50G
