nameSuffix: -small

bases:
- ../base

commonLabels:
  app: redis-small

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=30
    - threads=4
    - keymaximum=10000000
    - datasize=32
    - ratio=1:10
