apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: memtier
  labels:
    app: memtier

spec:
  serviceName: redis
  selector:
    matchLabels:
      app: memtier
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: memtier
    spec:
      containers:
        - name: memtire
          image: 100.64.176.12:80/wca/memtier_benchmark:d3ca4bb06f80a8eb83de6116ce6b7c3abe7ca153
          command:
            - bash
            - -c
            - "identifier=${podname#memtier-} service=${identifier%-[+[:digit:]]};
            taskset -c $memtire_cpus /usr/local/bin/memtier_benchmark --run-count=1 --server=redis-${identifier}.redis-${service} --threads=$threads --clients=$clients --pipeline=$pipeline --data-size=$datasize --random-data --hide-histogram --requests=allkeys --key-maximum=$keymaximum --ratio 1:0
            &&
            taskset -c $memtire_cpus memtier_benchmark_wrapper.pex \
            --command '/usr/local/bin/memtier_benchmark --run-count=1 --json-output-file=/dev/stdout --server=redis-${identifier}.redis-${service} --threads=$threads --clients=$clients --pipeline=$pipeline --data-size=$datasize --random-data --hide-histogram --requests=allkeys --key-maximum=$keymaximum --ratio $ratio $memtire_extra' \
            --log_level DEBUG \
            --stderr 0 \
            --labels '' \
            --metric_name_prefix 'redis_'
            "
          env:
            - name: podname
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
            - name: threads
              valueFrom: {configMapKeyRef: { name: redis-config, key: threads }}
            - name: clients
              valueFrom: {configMapKeyRef: { name: redis-config, key: clients }}
            - name: pipeline
              valueFrom: {configMapKeyRef: { name: redis-config, key: pipeline }}
            - name: datasize
              valueFrom: {configMapKeyRef: { name: redis-config, key: datasize }}
            - name: keymaximum
              valueFrom: {configMapKeyRef: { name: redis-config, key: keymaximum }}
            - name: ratio
              valueFrom: {configMapKeyRef: { name: redis-config, key: ratio }}
            - name: memtire_cpus
              valueFrom: {configMapKeyRef: { name: redis-config, key: memtire_cpus }}
            - name: memtire_extra
              valueFrom: {configMapKeyRef: { name: redis-config, key: memtire_extra }}

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  labels:
    app: redis

spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          command:
            - sh
            - -c
            - "taskset -c $redis_cpus redis-server --save '' --loglevel notice --databases 1 $redis_extra"
          env:
            - name: podname
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
            - name: redis_cpus
              valueFrom: {configMapKeyRef: { name: redis-config, key: redis_cpus }}
            - name: redis_extra
              valueFrom: {configMapKeyRef: { name: redis-config, key: redis_extra }}
