apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wca
  labels:
    team: monitoring
spec:
  selector:
    matchLabels:
      name: wca
  endpoints:
  - port: web
    interval: 1s
