resources:
  - sysbench-memory.yaml

commonLabels:
  workload: sysbench-memory

configMapGenerator:
  - name: sysbench-memory
    literals:
      - threads=4
      - cpus=0-1000
      - memory=16g
      - extra=

patchesStrategicMerge:
- resources.yaml
