# Full example for Mesos with anomalies stored in Kafka.

runner: !DetectionRunner
  node: !MesosNode
    mesos_agent_endpoint: 'http://127.0.0.1:5051'
    ssl_verify: True
    timeout: 5.
    ssl_client: !SSLCert  
      cert_path: "$PATH/apiserver-kubelet-client.crt"
      key_path: "$PATH/apiserver-kubelet-client.key"

  action_delay: 1.

  metrics_storage: !LogStorage
    output_filename: '/tmp/output_anomalies.log'

  anomalies_storage: !KafkaStorage
    topic: wca_anomalies
    max_timeout_in_seconds: 5.

  # Example use of external component.
  # Requires registration with -r example.external_package:ExternalDetector
  detector: !ExampleDetector

  # Decorate every metric with extra labels.
  extra_labels:
    env_id: "host"
