nameSuffix: -big
bases:
- ../base

commonLabels:
  app: memcached-mutilate-big

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - records=10000           # 100k
  - value=80000    # 80kB * 1M  <= 100GB
  - qps=20000      # 2M

patchesStrategicMerge:
  - resources.yaml
