---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wca

images:
  - name: wca
    newName: 100.64.176.12:80/wca
    newTag: devel

resources:
  - roles.yaml
  - daemonset.yaml

configMapGenerator:
  - name: wca-config
    files:
    - wca-config.yaml
