---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wca

resources:
  - roles.yaml
  - daemonset.yaml

configMapGenerator:
  - name: wca-config
    files:
    - wca-config.yaml
