loggers:
  wca: INFO
  wca.scheduler.server: INFO
  wca.scheduler.algorithms: TRACE
algorithm: !HierBAR
  data_provider: !ClusterDataProvider
    kubeapi: !Kubeapi
      host: !Env KUBERNETES_SERVICE_HOST
      port: !Env KUBERNETES_SERVICE_PORT
    prometheus: !Prometheus
      host: http://100.64.176.36
      port: 30900
      timeout: 5.0
      queries: !Queries
        APP_REQUESTED_RESOURCES_QUERY_MAP:
              cpu: 'ceil(max(max_over_time(task_requested_cpus[20m])) by (app))'
              mem: 'ceil(max(max_over_time(task_requested_mem_bytes[20m])) by (app) / 1e9)'
              membw_read: 'ceil(max(max_over_time (task_membw_reads_bytes_per_second[20m])) by (app) / 1e9)'
              membw_write: 'ceil(max(max_over_time (task_membw_writes_bytes_per_second[20m])) by (app) / 1e9)'
        MEMBW_CAPACITY_READ: 'ceil(sum(platform_nvdimm_read_bandwidth_bytes_per_second) by (nodename) / 1e9)'
        MEMBW_CAPACITY_WRITE: 'ceil(sum(platform_nvdimm_write_bandwidth_bytes_per_second) by (nodename) / 1e9)'
      time: '1582308900' # 21.02.2020 19:15
