apiVersion: v1
kind: ServiceAccount
metadata:
  name: wca-scheduler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wca-scheduler
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wca-scheduler
#  namespace: wca-scheduler
subjects:
  - kind: ServiceAccount
    name: wca-scheduler
roleRef:
  kind: Role
  name: wca-scheduler
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wca-scheduler
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wca-scheduler
#  namespace: wca-scheduler
subjects:
- kind: ServiceAccount
  name: wca-scheduler
  namespace: default
roleRef:
  kind: ClusterRole
  name: wca-scheduler
  apiGroup: rbac.authorization.k8s.io
