nameSuffix: -big
bases:
- ../base

commonLabels:
  app: redis-big

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=200
    - threads=8
    - datasize=1024
    - pipeline=10
    - ratio=1:10
