nameSuffix: -big
bases:
- ../base

commonLabels:
  app: redis-big

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=50
    - threads=8
    - keymaximum=50000000 # 50M
    - datasize=1024       # eff 50G
