apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 32135
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: grafana
