apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: prometheus-rules
  name: prometheus-wca-scheduler
  namespace: prometheus
spec:
  groups:
  - name: cluster-creatone-data-provider
    rules:
      - record: node_type
        expr: 'platform_mem_mode_size_bytes > 0'
        labels:
          nodetype: pmem

      - record: node_type
        expr: 'platform_mem_mode_size_bytes == 0'
        labels:
          nodetype: dram

      - record: node_type
        expr: 'platform_mem_mode_size_bytes < 0'
        labels:
          nodetype: unknown
      
      - record: app_profile
        expr: 'profile_app_2lm_score_max'
