apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: prometheus-rules
  name: prometheus-rules-wca-scheduler
spec:
  groups:
    - name: FFD
      rules:
        - record: task_membw_reads_bytes_per_second
          expr: rate(task_offcore_requests_demand_data_rd[30s]) * 64
        - record: task_membw_writes_bytes_per_second
          expr: rate(task_offcore_requests_demand_rfo[30s]) * 64
