tests:
  - test_case_name1:	
    tasks: 
      - /owca/task1 
      - /owca/task2

    allocator: !StaticAllocator
      rules:
        - name: Example first rule
          allocations:
            cpu_quota: 0.5
            cpu_shares: 10
    checks:
      - !FileCheck
        path: /tmp/owca
        value: '250'
        subvalue: '25'
      - !MetricCheck

  - test_case_name2:	
    tasks: 
      - /owca/task2 
      - /owca/task4

    allocator: !StaticAllocator
      rules:
        - name: Example second rule
          allocations:
            cpu_quota: 1.0
            cpu_shares: 20
    checks:
      - !FileCheck
        path: /tmp/owca
        value: '250'
        subvalue: '25'
      - !MetricCheck

