nameSuffix: -stream-medium
bases:
- ../base

commonLabels:
  app: stress-stream-medium

configMapGenerator:
- name: stress
  behavior: merge
  literals:
    - extra='--stream 1 --stream-l3-size=2g' # 24GB RSS
