nameSuffix: -stream-big
bases:
- ../base

commonLabels:
  app: stress-stream-big

configMapGenerator:
- name: stress
  behavior: merge
  literals:
    - extra='--stream 8 --stream-l3-size=2g' # 24GB RSS + 8 threads
