runner: !MeasurementRunner
  config: !MeasurementRunnerConfig
    node: !StaticNode
      tasks:
        - task1
    metrics_storage: !LogStorage
      output_filename: 'metrics.prom'
      overwrite: true
