nameSuffix: -small
bases:
- ../base

commonLabels:
  app: memcached-mutilate-small
  size: small

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=20000       # 20kB * 1M <= 25GB
  - qps=50000       # 50k per second

patchesStrategicMerge:
  - resources.yaml
