apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    workload: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: mutilate
          image: bplotka/mutilate
          env:
            - name: threads
              value: '4'
            - name: qps
              value: '500000'
            - name: time
              value: '5'
            - name: conns
              value: '1'
            - name: records
              value: '100000'
            - name: value
              value: '100000'

          command:
            - sh
            - -c
            - "./mutilate -T 1 -s 127.0.0.1:11211 --loadonly -r $records -V $value && \
               taskset -c 0-19 ./mutilate -C $conns -T $threads -t $time -s 127.0.0.1:11211 --noload --scan $qps:$qps:0 -r $records -V $value"

        - name: memcached
          env:
            - name: threads
              value: "4"
            - name: memory
              value: "128000"
          image: memcached
          command:
            - sh
            - -c
            - "taskset -c 20-39 memcached -t $threads -m $memory -u root"


