apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-memtier
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 1
              memory: 10G
            limits:
              cpu: 1
              memory: 10G
        - name: memtier
          resources:
            requests:
              cpu: 2
              memory: 1G
            limits:
              cpu: 2
              memory: 1G
