resources:
- memcached.yaml
- mutilate.yaml

commonLabels:
  workload: memcached-mutilate

configMapGenerator:
- name: memcached
  literals:
  - memory=200000 # MB a.k.a. 200G
  - threads=4
  - cpus=0-1000
  - extra=

- name: mutilate
  literals:
    - threads=8
    - cpus=0-1000
    - value=10000       # 10k
    - records=1000000   # 1M  = 10GB
    - qps=1000000       # 1M
    - conns=1
    - time=15          # seconds
    - extra=

patchesStrategicMerge:
  - resources.yaml
