# Basic minimal configuration to dump metrics on stderr with NOPAnomaly detector
runner: !DetectionRunner
  node: !MesosNode
  action_delay: 1.
  metrics_storage: !LogStorage
  anomalies_storage: !LogStorage
  detector: !NOPAnomalyDetector
