# Copyright (c) 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Full example with logger configuration per module, using external detector,
# storing logs in dedicated files and extra labels.

# Any package can be reconfigured to specifc level.
# To debug issues with loggers, run owca with enviornment variable:
# OWCA_DUMP_LOGGERS=True
loggers:
  example.external_package: debug  # Debug level for external component
  owca.perf: error
  owca.storage: info
  owca.runner: debug

runner: !DetectionRunner
  node: !MesosNode
  action_delay: 1.

  anomalies_storage: !LogStorage
    output_filename: '/tmp/input_metrics.log'
  metrics_storage: !LogStorage
    output_filename: '/tmp/output_anomalies.log'

  # Use external component.
  # Requires registration with -r example.external_package:ExternalDetector
  detector: !ExampleDetector

  # Decorate every metric with extra labels.
  extra_labels:
    env_id: "host"
