# Example of configuration to store metrics in dedicated Kafka topic.
runner: !DetectionRunner
  node: !MesosNode
  action_delay: 1.
  metrics_storage: !KafkaStorage
    topic: owca_metrics
    max_timeout_in_seconds: 5.
  anomalies_storage: !KafkaStorage
    topic: owca_anomalies
    max_timeout_in_seconds: 5.
  detector: !NOPAnomalyDetector
  rdt_enabled: False
