apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: memtier

spec:
  replicas: 0
  serviceName: redis
  selector:
    matchLabels:
      app: memtier
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: memtier
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        goal: load_generator
      containers:
        - name: memtier
          image: 100.64.176.12:80/wca/memtier_benchmark:e12ffdeaeaa12f8d9470bde0ed78b2a78cf855bc
          command:
            - bash
            - -c
            - "export identifier=${podname#memtier-}; export service=${identifier%-[+[:digit:]]};
            taskset -c $cpus memtier_benchmark --run-count=1 --json-out-file=/tmp/memtier_benchmark --server=redis-${identifier}.redis-${service} --threads=$threads --clients=$clients --pipeline=$pipeline --data-size=$datasize --random-data --hide-histogram --requests=allkeys --key-maximum=$keymaximum --ratio 1:0
            &&
            taskset -c $cpus memtier_benchmark_wrapper.pex \
            --command '\"while true; do memtier_benchmark --run-count=1 --test-time=10 --json-out-file=/tmp/memtier_benchmark --server=redis-${identifier}.redis-${service} --threads=$threads --clients=$clients --pipeline=$pipeline --data-size=$datasize --random-data --hide-histogram --requests=allkeys --key-maximum=$keymaximum --ratio $ratio $extra && sleep 1.2; done\"' \
            --log_level DEBUG \
            --stderr 0 \
            --labels '{\"workload\": \"redis\"}' \
            --metric_name_prefix 'redis_' \
            --subprocess_shell
            --storage_output_filename=/var/log/wrapper/metrics.prom
            "

          env:
            - name: podname
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
            - name: threads
              valueFrom: {configMapKeyRef: { name: memtier, key: threads }}
            - name: clients
              valueFrom: {configMapKeyRef: { name: memtier, key: clients }}
            - name: pipeline
              valueFrom: {configMapKeyRef: { name: memtier, key: pipeline }}
            - name: datasize
              valueFrom: {configMapKeyRef: { name: memtier, key: datasize }}
            - name: keymaximum
              valueFrom: {configMapKeyRef: { name: memtier, key: keymaximum }}
            - name: ratio
              valueFrom: {configMapKeyRef: { name: memtier, key: ratio }}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: memtier, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: memtier, key: extra }}
          volumeMounts:
            - name: var-log-wrapper
              mountPath: /var/log/wrapper

        - name: node-exporter
          image: prom/node-exporter:v0.18.1
          securityContext:
            privileged: true
          args:
            - --collector.textfile.directory=/var/log/wrapper
            - --web.disable-exporter-metrics
            - --no-collector.arp
            - --no-collector.bcache
            - --no-collector.bonding
            - --no-collector.conntrack
            - --no-collector.cpu
            - --no-collector.cpufreq
            - --no-collector.diskstats
            - --no-collector.edac
            - --no-collector.entropy
            - --no-collector.filefd
            - --no-collector.filesystem
            - --no-collector.hwmon
            - --no-collector.infiniband
            - --no-collector.ipvs
            - --no-collector.loadavg
            - --no-collector.mdadm
            - --no-collector.meminfo
            - --no-collector.netclass
            - --no-collector.netdev
            - --no-collector.netstat
            - --no-collector.nfs
            - --no-collector.nfsd
            - --no-collector.pressure
            - --no-collector.sockstat
            - --no-collector.stat
            - --no-collector.time
            - --no-collector.timex
            - --no-collector.uname
            - --no-collector.vmstat
            - --no-collector.xfs
            - --no-collector.zfs
            - --log.level=debug
          ports:
            - containerPort: 9100
              protocol: TCP
          volumeMounts:
            - name: var-log-wrapper
              mountPath: /var/log/wrapper
      volumes:
        - name: var-log-wrapper
          emptyDir: {}

  # required for workaround bug with kustomize https://github.com/kubernetes-sigs/kustomize/issues/504
  # when using commonLabels
  # fixed in 2.1.0 https://github.com/kubernetes-sigs/kustomize/commit/c470982ce5b96da82a757f088a842bb05d3bcdb4
  volumeClaimTemplates: []

