apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  labels:
    workload: redis

spec:
  replicas: 0
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: redis
          image: redis
          command:
            - sh
            - -c
            - "taskset -c $cpus redis-server --save '' --loglevel notice --databases 1 $redis_extra"
          env:
            - name: podname
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: redis, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: redis, key: extra }}

  # required for workaround bug with kustomize https://github.com/kubernetes-sigs/kustomize/issues/504
  # when using commonLabels
  volumeClaimTemplates: []
