loggers: {}
  #wca.wss: debug
runner: !DetectionRunner
  extra_labels: &node_labels
    node: node14
  action_delay: 5.0
  event_names:
    - mem_load_retired_local_pmm__rd180   # Retired load instructions with local Optane DC persistent memory as the data source  and the data request missed L3
    - mem_load_retired_local_dram__rd301
    - mem_inst_retired_all_loads__rd081
    - mem_inst_retired_all_stores__rd082
    - instructions
    - cycles
#    - memstalls__ra310  # Cycles while memory subsystem has an outstanding
    - mem_load_retired_local_pmm__rd180   # Retired load instructions with local Optane DC persistent memory as the data source  and the data request missed L3
    - mem_load_retired_local_dram__rd301
    - ocr_all_reads_l3_miss_local_dram_any_snoop__rb701003f840007f7
    - ocr_all_reads_l3_miss_local_pmm_any_snoop__ rb701003f804007f7
  wss_reset_interval: 1
  node: !KubernetesNode
    cgroup_driver: cgroupfs
    ssl: !SSL
      server_verify: False
      client_cert_path: "/home/ppalucki/wca_remote_pycharm/apiserver-kubelet-client.crt"
      client_key_path: "/home/ppalucki/wca_remote_pycharm/apiserver-kubelet-client.key"
    kubelet_endpoint: "https://100.64.176.40:10250"
    monitored_namespaces: ["default"]
  detector: !AEPDetector
    node_labels: *node_labels
  metrics_storage: !HTTPStorage
    port: 9100
  anomalies_storage: !HTTPStorage
    port: 9101
  enable_derived_metrics: true
  task_derived_metrics_generators_factory: !DefaultTaskDerivedMetricsGeneratorFactory
    extra_metrics:
      dram_hit: 'mem_load_retired_local_dram__rd301 / (mem_load_retired_local_pmm__rd180 + mem_load_retired_local_dram__rd301)'
      rw_ratio: 'delta("mem_inst_retired_all_loads__rd081") / delta("mem_inst_retired_all_stores__rd082")'
  platform_derived_metrics_generators_factory: !DefaultPlatformDerivedMetricsGeneratorsFactory
    extra_metrics:
      dram_hit: 'dram_total_mb_per_second / (pmm_total_mb_per_second+dram_total_mb_per_second)'
      dram_read_speed_gb: 'delta(cas_count_read) * 64/1024/1024/1024'


