resources:
- memcached.yaml
- sysbench.yaml
- redis.yaml
- stress.yaml

namespace: default

patchesStrategicMerge:
- replicas.yaml

patchesJson6902:
- target: { group: apps, version: v1, kind: StatefulSet, name: memcached}
  path: set_common.yaml

- target: { group: apps, version: v1, kind: StatefulSet, name: sysbench}
  path: set_common.yaml

- target: { group: apps, version: v1, kind: StatefulSet, name: redis}
  path: set_common.yaml

- target: { group: apps, version: v1, kind: StatefulSet, name: stress}
  path: set_common.yaml

configMapGenerator:
- name: memcached-config
  literals:
  - mutilate_threads=5
  - mutilate_cpus=0-1000
  - value=10000   # 100k
  - records=1000000 # 1M  = 10GB
  - memory=200000 # MB
  - qps=1000000
  - conns=1
  - time=15     # seconds
  - memcached_threads=4
  - memcached_cpus=0-1000
  - memcached_extra=
  - mutilate_extra=

- name: redis-config
  literals:
    - memtire_cpus=0-1000
    - redis_cpus=0-1000
    - datasize=1000
    - keymaximum=100000
    - ratio=1:1
    - redis_extra=
    - memtire_extra=

- name: sysbench-config
  literals:
    - threads=4
    - cpus=0-1000
    - memory=32
    - extra=

- name: stress-config
  literals:
    - extra='--stream 1 --stream-l3-size=256m'
    - cpus=0-1000
