apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysbench-small
  labels:
    workload: sysbench
spec:
  serviceName: sysbench-small
  podManagementPolicy: Parallel
  replicas: 0
  selector:
    matchLabels:
      app: sysbench-small
  template:
    metadata:
      labels:
        app: sysbench-small
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: sysbench
          env:
            - name: threads
              valueFrom: {configMapKeyRef: { name: sysbench-small, key: threads }}
            - name: memory
              valueFrom: {configMapKeyRef: { name: sysbench-small, key: memory }}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: sysbench-small, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: sysbench-small, key: extra }}
          image: severalnines/sysbench
          command:
          - sh
          - -c
          - "taskset -c $cpus sysbench --threads=$threads memory run --time=0 --memory-block-size=$memory --memory-total-size=0 --report-interval=1 $extra"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysbench-medium
  labels:
    workload: sysbench
spec:
  replicas: 0
  serviceName: sysbench-medium
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: sysbench-medium
  template:
    metadata:
      labels:
        app: sysbench-medium
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: sysbench
          env:
            - name: threads
              valueFrom: {configMapKeyRef: { name: sysbench-medium, key: threads }}
            - name: memory
              valueFrom: {configMapKeyRef: { name: sysbench-medium, key: memory }}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: sysbench-medium, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: sysbench-medium, key: extra }}
          image: severalnines/sysbench
          command:
            - sh
            - -c
            - "taskset -c $cpus sysbench --threads=$threads memory run --time=0 --memory-block-size=$memory --memory-total-size=0 --report-interval=1 $extra"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysbench-big
  labels:
    workload: sysbench
spec:
  replicas: 0
  serviceName: sysbench-big
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: sysbench-big
  template:
    metadata:
      labels:
        app: sysbench-big
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: sysbench
          env:
            - name: threads
              valueFrom: {configMapKeyRef: { name: sysbench-big, key: threads }}
            - name: memory
              valueFrom: {configMapKeyRef: { name: sysbench-big, key: memory }}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: sysbench-big, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: sysbench-big, key: extra }}
          image: severalnines/sysbench
          command:
            - sh
            - -c
            - "taskset -c $cpus sysbench --threads=$threads memory run --time=0 --memory-block-size=$memory --memory-total-size=0 --report-interval=1 $extra"
