nameSuffix: -medium
bases:
- ../base

commonLabels:
  app: memcached-mutilate-medium
  size: medium

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - value=40000     # 40kB * 1M <= 50G
  - qps=40000      # 40k

patchesStrategicMerge:
  - resources.yaml
