apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-mutilate
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 4
              memory: 50G # valueSize*records = 40kB * 1M <= 50GB
            limits:
              cpu: 4
              memory: 50G
        - name: mutilate
          resources:
            requests:
              cpu: 6
              memory: 1G
            limits:
              cpu: 6
              memory: 1G
