apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysbench
spec:
  serviceName: sysbench
  podManagementPolicy: Parallel
  replicas: 0
  selector:
    matchLabels:
      app: sysbench
  template:
    metadata:
      labels:
        app: sysbench
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: sysbench
          env:
            - name: threads
              valueFrom: {configMapKeyRef: { name: sysbench, key: threads }}
            - name: memory
              valueFrom: {configMapKeyRef: { name: sysbench, key: memory }}
            - name: cpus
              valueFrom: {configMapKeyRef: { name: sysbench, key: cpus }}
            - name: extra
              valueFrom: {configMapKeyRef: { name: sysbench, key: extra }}
          image: severalnines/sysbench
          command:
            - sh
            - -c
            - "taskset -c $cpus sysbench --threads=$threads memory run --time=0 --memory-block-size=$memory --memory-total-size=0 --report-interval=1 $extra"
  # required for workaround bug with kustomize https://github.com/kubernetes-sigs/kustomize/issues/504
  # when using commonLabels
  volumeClaimTemplates: []
