nameSuffix: -small
bases:
- ../base

commonLabels:
  app: sysbench-memory-small

patchesStrategicMerge:
  - resources.yaml

configMapGenerator:
- name: sysbench-memory
  behavior: merge
  literals:
    - threads=3
    - memory=1g
    - report_interval=1
